FORMAT: 1A
HOST: https://data.thistothat.io/

# ThisToThat

ThisToThat is a simple API that converts things from one format to another.

# Group Commodities

## Harmonized System [/commodities/hs/{code}]

+ Parameters
    + code (number) - chapter, heading or subheading HS code

### Get Harmonized Commodity Description [GET]

+ Response 200 (application/json)

        {
            "code": "060314",
            "description": "Flowers, cut; chrysanthemums, flowers and buds of a kind suitable for bouquets or ornamental purposes, fresh",
            "level": "subheading"
        }
        
+ Response 400 (application/json)

        {
            "error": "invalid_code",
            "message": "Expected a chapter, heading or subheading HS code."
        }